---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 65b551e9b34643695ff4ca57e38759f8ec7a7a6b
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: prd-customer-interface
  labels:
    expose: "true"
    app: i-disa-prd-customer-interface
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-disa-prd-customer-interface
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-disa-prd-customer-interface
    provider: fabric8
    group: com.redhat
