---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: b27426d13cef358d2de22b6fea1fb2e7fdffd5f8
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: test-disa-supplier-logging
  labels:
    expose: "true"
    app: i-disa-test-supplier-logging
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-disa-test-supplier-logging
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-disa-test-supplier-logging
    provider: fabric8
    group: com.redhat
