---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    expose: "true"
    app: i-ptg_get_pc
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-ptg_get_pc
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: i-ptg_get_pc
