---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 0e0366c868ca037a9e84136bcb1c9880ac5d4a92
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: prd-supplier-interface
  labels:
    expose: "true"
    app: i-disa-prd-supplier-interface
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-disa-prd-supplier-interface
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-disa-prd-supplier-interface
    provider: fabric8
    group: com.redhat
