---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 459de79ebc6a72a586d30f83d9221c6878ab4664
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/git-branch: test-footprint-interface
    labels:
      expose: "true"
      app: i-disa-test-footprint-interface
      provider: fabric8
      version: 0.1.0
      group: com.redhat
    name: i-disa-test-footprint-interface
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: i-disa-test-footprint-interface
      provider: fabric8
      group: com.redhat
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 459de79ebc6a72a586d30f83d9221c6878ab4664
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/git-branch: test-footprint-interface
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=i-disa-test-footprint-interface&var-version=0.1.0
    labels:
      app: i-disa-test-footprint-interface
      provider: fabric8
      version: 0.1.0
      group: com.redhat
    name: i-disa-test-footprint-interface
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: i-disa-test-footprint-interface
      provider: fabric8
      group: com.redhat
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 459de79ebc6a72a586d30f83d9221c6878ab4664
          fabric8.io/iconUrl: img/icons/camel.svg
          fabric8.io/git-branch: test-footprint-interface
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=i-disa-test-footprint-interface&var-version=0.1.0
        labels:
          app: i-disa-test-footprint-interface
          provider: fabric8
          version: 0.1.0
          group: com.redhat
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":1}}}'
          - name: JAVA_APP_JAR
            value: i-disa-test-footprint-interface-0.1.0.jar
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: i-disa-test-footprint-interface:0.1.0
          imagePullPolicy: IfNotPresent
          name: i-disa-test-footprint-interface
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8081
            name: sunproxyadmin
            protocol: TCP
          resources:
            limits:
              cpu: "1.0"
            requests:
              cpu: "0.2"
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - i-disa-test-footprint-interface
        from:
          kind: ImageStreamTag
          name: i-disa-test-footprint-interface:0.1.0
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      expose: "true"
      app: i-disa-test-footprint-interface
      provider: fabric8
      version: 0.1.0
      group: com.redhat
    name: i-disa-test-footprint-interface
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: i-disa-test-footprint-interface
